parameters:
     maith_common.bcucotizador.class: Maith\Common\AdminBundle\Services\BcuCotizadorService
     maith_common.admin.parameters.class: Maith\Common\AdminBundle\Services\MaithParametersService
     maith_common.admin.twig.avatar.class: Maith\Common\AdminBundle\Twig\mAvatarExtension
     maith_common.admin.listener.delete.class: Maith\Common\AdminBundle\Listener\DeleteListener
     maith_common.admin.galery.manager.class: Maith\Common\AdminBundle\Model\GalleryManager
     maith_common.cache.class: Doctrine\Common\Cache\FilesystemCache
     maith_common.email.service.class: Maith\Common\AdminBundle\Services\MaithEmailService
#    maith_common_admin.example.class: Maith\Common\AdminBundle\Example
     maith_common.email.service.multiplemailers: 1
     maith_common.email.service.maximunperhour: 999

services:
    maith_common_admin.upload:
        class: Maith\Common\AdminBundle\Listener\RequestListener
        arguments: [%maith_common_admin.upload_token%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    maith_common_admin.twig.maith_m_avatar:
        class: %maith_common.admin.twig.avatar.class%
        arguments:
             - "@doctrine.orm.entity_manager"
             - "%kernel.root_dir%"
             - "@maith_common.cache"
        tags:
            -  { name: twig.extension }

    maith_common_delete_listener:
        class: %maith_common.admin.listener.delete.class%
        tags:
            -  { name: doctrine.event_listener, event: preRemove }

    maith_common.bcucotizador:
        class: %maith_common.bcucotizador.class%
        arguments: ["@doctrine.orm.entity_manager"]

    media_gallery_manager:
        class: %maith_common.admin.galery.manager.class%
        arguments:
             - "%kernel.root_dir%"

    maith_common.parameters:
        class: %maith_common.admin.parameters.class%
        arguments: ["%kernel.root_dir%"]

    maith_common.cache:
        class: %maith_common.cache.class%
        arguments: ["%kernel.cache_dir%"]

    maith_common.email:
        class: "%maith_common.email.service.class%"
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "@logger", "%maith_common.email.service.multiplemailers%", "%maith_common.email.service.maximunperhour%"]
        lazy: true